### ISSUE TITLE
Item lists example, a wish

### ISSUE THREAD

**Issue by stappersg** [tailhook/rust-quire#20]
Hi,

Here a wish for providing an example that handles item lists.

Example of *item lists*

```yaml
team:
  - Alice
  - Bob
  - Claire
  - David
vehicles:
  - Jeep
  - Landrover
```

How should the *rust source code* for reading that look like?

Regards
Geert Stappers
